heads:
  master:
    tests/no_env_vars:
    tests/create_file:
      foo: 'bar'
  develop:
    deploy/rsync:
      source: 'htdocs/'
      destination: 'rpflorence@raflorence.net:/home/rpflorence/test'
